[package]
name = "mine"
version = "0.1.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[[bin]]
name = "tracer"
path = "src/tracer.rs"

[[bin]]
name = "tracee"
path = "src/tracee.rs"

[build-dependencies]
cc = "*"

[dependencies]
libc = "*"
nix = "*"
